name: 'Recovery Builder OFRP R11.1'

on:

  workflow_dispatch:

    inputs:

      manifest:

        description: 'Recovery Manifest URL with -b branch'

        required: true

        default: 'https://gitlab.com/OrangeFox/Manifest.git -b fox_9.0'

      vendor:

        description: 'Device Company / OEM / Vendor, i.e., xiaomi'

        required: true

        default: 'intex'

      codename:

        description: 'Device Codename i.e rosy'

        required: true

        default: 'Cloud_Q11'

      dt_link:

        description: 'Device Tree link, with optional -b branch'

        required: true

        default: 'https://gitlab.com/aryankaran/TWRP-OFRP-tree-intex-Cloud-Q11.git -b fox_9.0_R11.1'

      kernel_link:

        description: 'Kernel repo link with optional -b branch, Use if not prebuilt'

        required: false

      req_qcom_commonsys:

        description: 'If require QCOM commonsys, set this to true, i.e., SHRP needs this'

        required: true

        default: 'false'

      cryptfs_fix:

        description: 'If require to fix cryptfs_hw conflict, set this to true'

        required: true

        default: 'false'

      target:

        description: 'Build Target, i.e., recoveryimage'

        required: true

        default: 'recoveryimage'

      flavor:

        description: 'Build flavor, i.e., userdebug or eng'

        required: true

        default: 'eng'

      extra_cmd:

        description: 'Do extra commands followed by && after each cmds, i.e rm -rf repo && git clone repo'

        required: false

env:

  MANIFEST: ${{ github.event.inputs.manifest }}

  DT_LINK: ${{ github.event.inputs.dt_link }}

  VENDOR: ${{ github.event.inputs.vendor }}

  CODENAME: ${{ github.event.inputs.codename }}

  KERNEL_LINK: ${{ github.event.inputs.kernel_link }}

  TARGET: ${{ github.event.inputs.target }}

  FLAVOR: ${{ github.event.inputs.flavor }}

  EXTRA_CMD: ${{ github.event.inputs.extra_cmd }}

  REQ_QCOM_COMMONSYS: ${{ github.event.inputs.req_qcom_commonsys }}

  CRYPTFS_FIX : ${{ github.event.inputs.cryptfs_fix }}

  TZ: Asia/Kolkata

jobs:

  build:

    runs-on: ubuntu-20.04

    steps:

      - name: Checkout

        uses: actions/checkout@main

      - name: Cleanup Space

        uses: rokibhasansagar/slimhub_actions@main

      - name: Initializing Build Environment

        run: bash prepare.sh

      - name: Make ${{ env.TARGET }} for ${{ env.CODENAME }}

        run: bash builder.sh

      - name: Release Builds

        uses: "marvinpinto/action-automatic-releases@latest"

        with:

         repo_token: "${{ secrets.GITHUB_TOKEN }}"

         automatic_release_tag: "OrangeFox_intex-R11.1"

         prerelease: false

         title: "OrangeFox recovery version R11.1 ...üòçüòç"

         files: |

            /home/runner/work/Recovery-automation/Recovery-automation/work/out/target/product/*/*.img
            /home/runner/work/Recovery-automation/Recovery-automation/work/out/target/product/*/*.zip
